"""Domain model: plans, constraints, approvals, and external operations.

This package depends on the standard library only. It contains no HTTP client,
database session, model SDK, or user interface code.
"""

from health_assistant.domain.approvals import (
    Approval,
    authorize_execution,
    fingerprint_items,
    grant_approval,
    validation_report_for,
)
from health_assistant.domain.constraints import (
    Constraint,
    ConstraintKind,
    ConstraintSet,
    ConstraintSeverity,
    ConstraintSource,
    normalize_token,
)
from health_assistant.domain.errors import DomainError
from health_assistant.domain.identifiers import (
    ApprovalId,
    ConstraintId,
    OperationId,
    PlanId,
    PlanItemId,
    UserId,
)
from health_assistant.domain.operations import (
    ALLOWED_TRANSITIONS,
    Lease,
    OperationKind,
    OperationState,
    ProviderOutcome,
    ToolOperation,
    cancel,
    claim,
    confirm,
    expire_lease,
    propose,
    reconcile,
    record_ambiguous_outcome,
    record_failure,
    record_success,
    request_confirmation,
    retry,
)
from health_assistant.domain.plans import (
    AddItem,
    CompletionStatus,
    PlanChange,
    PlanItem,
    PlanItemCategory,
    PlanVersion,
    RecordCompletion,
    RemoveItem,
    ReplaceItem,
    revise,
)
from health_assistant.domain.scheduling import Clock, TimeWindow
from health_assistant.domain.validation import (
    Finding,
    ValidationOutcome,
    ValidationReport,
    validate_plan,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AddItem",
    "Approval",
    "ApprovalId",
    "Clock",
    "CompletionStatus",
    "Constraint",
    "ConstraintId",
    "ConstraintKind",
    "ConstraintSet",
    "ConstraintSeverity",
    "ConstraintSource",
    "DomainError",
    "Finding",
    "Lease",
    "OperationId",
    "OperationKind",
    "OperationState",
    "PlanChange",
    "PlanId",
    "PlanItem",
    "PlanItemCategory",
    "PlanItemId",
    "PlanVersion",
    "ProviderOutcome",
    "RecordCompletion",
    "RemoveItem",
    "ReplaceItem",
    "TimeWindow",
    "ToolOperation",
    "UserId",
    "ValidationOutcome",
    "ValidationReport",
    "authorize_execution",
    "cancel",
    "claim",
    "confirm",
    "expire_lease",
    "fingerprint_items",
    "grant_approval",
    "normalize_token",
    "propose",
    "reconcile",
    "record_ambiguous_outcome",
    "record_failure",
    "record_success",
    "request_confirmation",
    "retry",
    "revise",
    "validate_plan",
    "validation_report_for",
]
